# Generated by Django 4.2.6 on 2023-11-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='content_type',
            field=models.CharField(default='audio/mpeg', max_length=50),
            preserve_default=False,
        ),
    ]
