# Generated by Django 4.2.6 on 2023-11-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_files', '0002_audiofile_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='file',
        ),
    ]
