# Generated by Django 4.2.6 on 2023-11-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_files', '0003_remove_audiofile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='file',
            field=models.FileField(default='audio/mpeg', upload_to='audio/'),
            preserve_default=False,
        ),
    ]
